### ISSUE TITLE
correcture for ms paint

### ISSUE THREAD

**Issue by chuckhedgehog** [i5ik/jspaint.exe#5]
in the original ms-paint (1998) i 
01)   1st OPEN a new picture
02)   SELECT
03)  select part of picture (50*50)
04) choose EDIT/COPY TO

01-04 saves a picture in your version in PNG-format

the original from 1998 saves a picture in BMP-format (which is better).
Win98 Second Edition English/mspaint.exe
'
a newer version (2019) for ms-paint:find download in:
http://basic4gl.proboards.com/board/5/basic4gl-demo-programs
click minesweeper [september_2021]
please send e-mail to:chuck.summer@mail.com

**Comment by crisdosaygo** [comment]
Thank you  @chuckhedgehog 

Yes I noticed that, too, about the PNG, with no "Save As". Hmmm, the Paint I use for this comes from https://github.com/1j01/jspaint

So I could try updating that. 

In terms of using the Paint executable you provide as inspiration, that's a good idea, but improving the Paint aspect of this is not my scope, intention or desire, so I won't do that. I'll only update it from someone else.

In terms of using the Paint you provide as an actual source, like using WASM, that would involve somehow compiling this Paint into something that can run on an x86 emulator in JS. But I think that would be unlikely to work on emulator + paint executable, because paint calls lots of Windows APIs (presumably, I'm not expert) and they would not be present in the x86 emulator. 

Interesting project in an off itself, "tree shake" a Windows OS down to the absolute bare minimum required to run a paint executable on an x86 emulator, then run that in JavaScript. But that is not something that I'm going to do. Right now at least, anyway. 

So I won't do anything on this, right now or ever, but I will update this paint executable in future, probably anyway. Tho I don't think that will necessarily solve your issue. As I don't think https://github.com/1j01/jspaint has the new "Save As" functionality.

Anyway, thanks for the issue, and thanks for indirectly pointing me to see "BASIC 4GL" -- looks very interesting! :)

**Comment by crisdosaygo** [comment]
Someone stripped down Windows to be 5 MB Windows 98

http://web.archive.org/web/20090209050149/http://www.etek.chalmers.se/~e8gus/nano98/

So this would be possible to get that Windows 98 that's 5 MB and run it on an emulator inside JavaScript just to be able to run the original Microsoft paint 

As a cross-platform native desktop app
